#ifndef _tasks_h_
#define _tasks_h_ 1

#define DEFAULT_FIRST_USER_PRIORITY 8
#define TC2_FIRST_USER_PRIORITY 0
#define DEFAULT_TRAIN_CONTROL_PRIORITY 5
#define TC2_CONTROL_PLANE_PRIORITY 4
#define TC2_TRAIN_CONTROL_PRIORITY TC2_CONTROL_PLANE_PRIORITY
#define TC2_DISPATCH_TICKER_PRIORITY TC2_CONTROL_PLANE_PRIORITY
#define TC2_SENSOR_COURIER_PRIORITY TC2_CONTROL_PLANE_PRIORITY
#define TC2_TERMINAL_NOTIFIER_PRIORITY TC2_CONTROL_PLANE_PRIORITY
#define TC2_BUILD_MARKER \
        "TC2 build marker: stage68-compound-zone-watchdog-latch\r\n"

void FirstUserTask(void);
void TestTask(void);

#endif
